name: CloneRepository

on:
  push:
    branches:
      - sandbox

jobs:
  clone_repository:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Clone etiflux Repository
      run: |
        git clone https://github.com/fakhrihuseynov/etiflux.git temp_clone
        cd temp_clone
        git checkout -b sandbox
        
        # Set the PAT for authentication
        export GITHUB_TOKEN=$PAT_TOKEN
        
        # Push the sandbox branch to the target repository
        git push "https://github.com/fakhrihuseynov/eti-mses-us-customer.git" sandbox
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
