name: CloneRepository

on:
  push:
    branches:
      - sandbox

jobs:
  clone_repository:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Clone etiflux Repository
      run: |
        git clone https://github.com/fakhrihuseynov/etiflux.git temp_clone
        cd temp_clone
        git remote add target-repo https://github.com/fakhrihuseynov/eti-mses-us-customer.git
        git config user.email "fexrihuseynov@gmail.com"
        git config user.name "Fakhri Huseynov"
        git checkout -b sandbox
        git push target-repo sandbox
