name: CloneRepository

on:
  push:
    branches:
      - sandbox

jobs:
  clone_repository:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Clone etiflux Repository
      run: |
        git clone https://github.com/fakhrihuseynov/etiflux.git temp_clone
        cd temp_clone
        git remote add target-repo https://github.com/fakhrihuseynov/eti-mses-us-customer.git
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git checkout -b sandbox
        
        # Create some commits or changes to the sandbox branch
        touch example_file.txt
        git add .
        git commit -m "Adding example_file.txt"
        
        # Push the sandbox branch to the target repository
        git push "https://$TARGET_REPO_TOKEN@github.com/fakhrihuseynov/eti-mses-us-customer.git" sandbox
      env:
        TARGET_REPO_TOKEN: ${{ secrets.ARM_SEC }}
