name: NewRepos

on:
  push:
    branches:
      - sandbox

jobs:
  clone_repository:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ARM-templates }}
    
    - name: Remove Temporary Clone Directory
      run: rm -rf temp_clone
    
    - name: Clone Repository
      run: |
        git clone https://github.com/fakhrihuseynov/etiflux.git temp_clone
        cd temp_clone
        git checkout main
    
    - name: Push to Target Repository
      run: |
        git push https://github.com/fakhrihuseynov/eti-mses-us-customer.git HEAD:sandbox
        
    # Other steps you might want to include here...
