name: RunTests

on:
  workflow_dispatch: 
  push:
    branches: 
      - sandbox
      - prod


jobs:  
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone repo
      env: 
        PAT: ${{ secrets.ARM_SEC }}

        userName: fakhrihuseynov
        email: fexrihuseynov@gmail.com
      run: |
        git config --global user.email $email
        git config --global user.name $userName
        git clone https://fakhrihuseynov:$PAT@github.com/fakhrihuseynov/alma
        cd alma
        git remote add fruit https://fakhrihuseynov:$PAT@github.com/ETI-Software-Solutions/eti-gitops-templates.git
        git fetch fruit
        # git commit -m "my message"
        git merge fruit/main --allow-unrelated-histories
        git push origin sandbox

    - name: Check existing repo
      run: | 
        git clone https://fakhrihuseynov:$PAT@github.com/fakhrihuseynov/alma
        cd alma
        cat infra/tenant/voyager/.gitignore

    # - name: Git push
    #   env: 
    #     PAT: ${{ secrets.ARM_SEC }}
    #   run: | 
    #     git push --set-upstream $PAT@github.com/fakhrihuseynov/eti-mses-us-customer.git sandbox


# name: CloneRepository

# on:
#   push:
#     branches:
#       - sandbox

# jobs:
#   clone_repository:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2
      
#     - name: Clone etiflux Repository
#       run: |
#         git clone https://github.com/fakhrihuseynov/etiflux.git temp_clone
#         # git checkout -b sandbox        
#         # Push the sandbox branch to the target repository
#         # git push "https://github.com/fakhrihuseynov/eti-mses-us-customer.git" sandbox

#     - name: git push changes
#       uses: appleboy/git-push-action@v0.0.2
#       with:
#           author_email: fexrihuseynov@gmail.com
#           author_name: GiteaBot
#           branch: sandbox
#           commit: true
#           commit_message: "[skip ci] Updated changes by gitea bot"
#           remote: git@github.com:fakhrihuseynov/eti-mses-us-customer.git
#           ssh_key: ${{ secrets.ARM_SEC }}     


#     # - name: Pushes to public repository
#     #   id: push_directory
#     #   uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
#     #   env:
#     #       SSH_DEPLOY_KEY: ${{ secrets.ARM_SEC }}
#     #   with:
#     #       source-directory: temp_clone/
#     #       destination-github-username: 'fakhrihuseynov'
#     #       destination-repository-name: 'eti-mses-us-customer'
#     #       user-email: fexrihuseynov@gmail.com
#     #       commit-message: pushed from $GITHUB_REF
#     #       target-branch: sandbox
