name: NewRepos

on:
  push:
    branches:
      - sandbox

jobs:
  clone_repository:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Remove Temporary Clone Directory
      run: rm -rf temp_clone
    
    - name: Clone Repository
      run: |
        git clone https://github.com/fakhrihuseynov/etiflux.git
        git remote add origin https://github.com/fakhrihuseynov/eti-mses-us-customer.git
        git push origin sandbox

        # git checkout sandbox
        # git config --global --add safe.directory /github/home
        # mkdir eti

    
    # - name: Git Push Action
    #   uses: x-actions/git-push@v1.0
    #   env:
    #     GITHUB_EMAIL: "fexrihuseynov@gmail.com"
    #     GITHUB_USERNAME: "fakhrihuseynov"
    #     PUBLISH_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/fakhrihuseynov/eti-mses-us-customer.git HEAD:sandbox
    #     PUBLISH_BRANCH: sandbox
    #     PUBLISH_DIR: ./eti
    #     # DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      
    
    # - name: Push to Target Repository
    #   run: |
    #     git push https://github.com/fakhrihuseynov/eti-mses-us-customer.git HEAD:sandbox
        
    # Other steps you might want to include here...
