name: NewRepos

on:
  push:
    branches:
      - sandbox

jobs:
  clone_repository:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Clone Repository
      run: |
        git clone https://github.com/fakhrihuseynov/etiflux.git
        git checkout sandbox
        mkdir eti

    - name: Configure Git
      run: |
        git config user.email "fexrihuseynov@gmail.com"
        git config user.name "fakhrihuseynov"

    - name: Add and Commit Changes
      run: |
        cd eti
        touch README.md
        git add .
        git commit -m "Add README"
    
    - name: Push Changes
      run: |
        cd eti
        git remote add origin https://github.com/fakhrihuseynov/eti-mses-us-customer.git
        git push origin sandbox
