name: NewRepos

on:
  push:
    branches:
      - sandbox

jobs:
  clone_repository:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Remove Temporary Clone Directory
      run: rm -rf temp_clone
    
    - name: Clone Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/fakhrihuseynov/etiflux.git temp_clone
          git push  https://github.com/fakhrihuseynov/eti-mses-us-customer.git HEAD:sandbox
          # git push https://fakhrihuseynov:${{ secrets.GITHUB_TOKEN }}@github.com/fakhrihuseynov/eti-mses-us-customer.git HEAD:sandbox
          cd temp_clone
          git checkout main
        
        # Replace 'sandbox' with your target branch name if needed
        # Use the provided PAT for authentication
        # git config user.name "fakhrihuseynov"
        # git config user.email "fexrihuseynov@gmail.com"
        # git push https://fakhrihuseynov:${{ secrets.ARM-templates }}@github.com/fakhrihuseynov/eti-mses-us-customer.git HEAD:sandbox
