name: RunTests

on: [push, pull_request]

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Make Save directory1
      run: | 
        git config --global --add safe.directory '*'  

    - name: Clone repo
      uses: actions/checkout@master
      with:
        repository: fakhrihuseynov/etiflux
        ref: refs/heads/main
        path: public
      
    - name: Make Save directory2
      run: | 
        git config --global --add safe.directory '*'  

    - name: Push to Github
      uses: x-actions/git-push@v1
      with:
        GITHUB_EMAIL: "fexrihuseynov@gmail.com"
        GITHUB_USERNAME: "fakhrihuseynov"
        PUBLISH_REPO: https://${{ secrets.ARM_SEC }}@github.com/fakhri/eti-mses-us-customer.git
        PUBLISH_BRANCH: sandbox
        PUBLISH_DIR: ./public
        # DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}


# name: CloneRepository

# on:
#   push:
#     branches:
#       - sandbox

# jobs:
#   clone_repository:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2
      
#     - name: Clone etiflux Repository
#       run: |
#         git clone https://github.com/fakhrihuseynov/etiflux.git temp_clone
#         # git checkout -b sandbox        
#         # Push the sandbox branch to the target repository
#         # git push "https://github.com/fakhrihuseynov/eti-mses-us-customer.git" sandbox

#     - name: git push changes
#       uses: appleboy/git-push-action@v0.0.2
#       with:
#           author_email: fexrihuseynov@gmail.com
#           author_name: GiteaBot
#           branch: sandbox
#           commit: true
#           commit_message: "[skip ci] Updated changes by gitea bot"
#           remote: git@github.com:fakhrihuseynov/eti-mses-us-customer.git
#           ssh_key: ${{ secrets.ARM_SEC }}     


#     # - name: Pushes to public repository
#     #   id: push_directory
#     #   uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
#     #   env:
#     #       SSH_DEPLOY_KEY: ${{ secrets.ARM_SEC }}
#     #   with:
#     #       source-directory: temp_clone/
#     #       destination-github-username: 'fakhrihuseynov'
#     #       destination-repository-name: 'eti-mses-us-customer'
#     #       user-email: fexrihuseynov@gmail.com
#     #       commit-message: pushed from $GITHUB_REF
#     #       target-branch: sandbox
